repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.0.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=51200']
    -   id: check-ast
        language_version: python3.6
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: debug-statements
        language_version: python3.6
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: forbid-new-submodules
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: system
        name: Pylint
        entry: python -m pylint.__main__
        language: system
        files: \.py$
    -   id: system
        name: py.test
        entry: py.test --color=yes
        language: system
        files: \.py$
        pass_filenames: false
