image: python:3.5-onbuild

pipelines:
  default:
    - step:
        script:
          # TODO(m3drano): This should be run with Bazel.
          - ./main.py --debug --trace --max_runs=1 --config=config/dev.ini --per_pc --per_hour
