image: python:3.5.1

pipelines:
  default:
    - step:
        script:
          - pip install -Ur requirements.txt
          # TODO(m3drano): This should be run with Bazel.
          - ./main.py --debug --config=config/dev.ini
