image: python:3.5

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y --no-install-recommends python3-matplotlib python3-numpy python3-scipy
          - pip3 install injector simpy
          # TODO(m3drano): This should be run with Bazel.
          - python3 main.py --debug --trace --max_runs=1 --config=config/dev.ini --per_pc --per_hour
