image: m3drano/python-git-lfs

pipelines:
  default:
    - step:
        script:
          - git remote set-url origin "https://${BITBUCKET_REPO_OWNER}:${APP_PASSWD}@bitbucket.org/${BITBUCKET_REPO_OWNER}/${simulation}.git"
          - TRACE=2 git-lfs pull
          - pip3 install -Ur requirements.txt
          - bazel --batch run :main -- --debug --trace --max_runs=1 --config=config/dev.ini --per_pc --per_hour
