#  -*- mode: python -*-

py_binary(
    name = "benchmark",
    srcs = ["benchmark.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
    deps = ["//simulation:distribution"],
)

py_binary(
    name = "ks",
    srcs = ["ks.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
    deps = ["//simulation:distribution"],
)
